[build]
  # Thư mục chứa file build (nếu có)
  publish = "."
  
  # Thư mục chứa file build (nếu sử dụng build tool)
  # publish = "dist"
  
  # Command build (nếu cần)
  # command = "npm run build"

[build.environment]
  # Biến môi trường cho build
  NODE_VERSION = "18"

# Cấu hình deploy
[context.production]
  # Branch chính để deploy
  branch = "main"
  
  # Ép chuyển hướng sang HTTPS cho mọi request (nếu chưa bật trong Dashboard)
  [[redirects]]
    from = "http://*"
    to = "https://:splat"
    status = 301
    force = true
  
  # Cấu hình redirects
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

# Cấu hình headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cấu hình form handling (nếu có form)
[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200
# Cấu hình 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404 
